### ISSUE TITLE
Playback commands

### ISSUE THREAD

**Issue by rockstar2020** [mikejac/node-red-contrib-google-smarthome#113]
Hi there,
I can control turning on/off, adjust volume or open any app on a streaming box or streaming stick via voice command but have not been successful to control playback commands such as Play, Pause, Next, ...
I have selected all supported commands in "Transport control" section but still no luck!
What am I missing?

![image](https://user-images.githubusercontent.com/35903046/110212221-586a6b80-7e68-11eb-86ec-0d0e7775acff.png)

Cheers

**Comment by ckhmer1** [comment]
Hi,
could You please add the node-red logs?
Thanks

**Comment by rockstar2020** [comment]
Hi,
Thanks for your reply.
I don't see any logs in Node-Red. The command doesn't even reach Node-Red.
On Google Assistant Though, after I execute the voice command (ie "Pause Fire TV") it says something like "Alright" followed by "Looks like xxxx is unavailable right now". 
NOTE: xxxx is the name of my Smart Home.
Any other commmands like "Launch app1 on Fire TV" or "Increase volume on Fire TV by 20" works perfectly fine.

Many thanks in advance
Cheers

**Comment by ckhmer1** [comment]
Hi,
I've just sent the fix for that.
Thanks for reporting.
Claudio

**Comment by rockstar2020** [comment]
Hi @ckhmer1,
Thanks for the quick fix.
I made the changes manually and can now confirm the issue is fixed.

Have a nice day!
Cheers

**Comment by rockstar2020** [comment]
Sorry, I had to re-open the issue because I noticed another minor issue.
I can see in your media.js code you report the playback state as "PLAYING" for commands such as "action.devices.commands.mediaSeekRelative" and "action.devices.commands.mediaSeekToPosition" which doesn't seem right to me.
In other words to execute a voice command like "Skip Streamer by 2 min" or "Seek Streamer to 45 min" the playback state in Node-Red always is "PLAYING".
I made the following change in media.js which works perfectly fine by reporting correct state but in addition to this it would be great if the actual minutes to skip or seek is also passed from Google to Node-Red. Is it possible to add this parameter as well?
Can you also include the following change in your PR anyways?

**The change I made to media.js:**
            _else if (command.command == 'action.devices.commands.mediaSeekRelative') {
                if (command.params.hasOwnProperty('relativePositionMs')) {
                    const relative_position_ms = command.params['relativePositionMs'];
                    params['playbackState'] = 'SKIPPING';
                    executionStates.push('online', 'playbackState');
                    return ok_result;
                }
            }
            else if (command.command == 'action.devices.commands.mediaSeekToPosition') {
                if (command.params.hasOwnProperty('absPositionMs')) {
                    const abs_position_ms = command.params['absPositionMs'];
                    params['playbackState'] = 'SEEKING';
                    executionStates.push('online', 'playbackState');
                    return ok_result;
                }
            }_

**Comment by rockstar2020** [comment]
I checked the developers documents on Google Actions and can see the paramter you need to pass is "relativePositionMs".
Thank you in advance

Cheers

**Comment by ckhmer1** [comment]
Hi,
I don't know where you get the SKIPPING and SEEKING values but are not valid ones.
The valid states are https://developers.google.com/assistant/smarthome/traits/mediastate

I've updated my patch to add the "relativePositionMs" and "absPositionMs" values.

Claudio

**Comment by rockstar2020** [comment]
Yeah I know, I just added those states as a work around to distinguish between a skip/seek and play commands. 
Now after the changes being made I can see the paramters are now passed so I can use the original "PLAYING" state.
Thanks for making those changes.
Please allow me to give it a try and then let you know how it goes.

Cheers

**Comment by ckhmer1** [comment]
Hi,
in the node output, there is also the command send by google, 
You can also use it to distinguishing between commands.

**Comment by rockstar2020** [comment]
OK, I did try the changes.
If I have a stand alone media node and run a command everything works perfectly fine and the message object is exactly what's expected.
But the moment I add a function node right after the media node I get the following error.
For test purposes I added a very simple function node that only had "return msg;" in it.
What do you think could have caused this error?

![image](https://user-images.githubusercontent.com/35903046/110248565-d51c4900-7f3f-11eb-9fa0-949d55659683.png)

**Comment by rockstar2020** [comment]
Further info:
I added an inject node to update the playback state of the media node manually and I get exactly the same error.
Hoping it helps to narrow down the root cause of the issue.
Here is a snapshot of my Inject node:

![image](https://user-images.githubusercontent.com/35903046/110248836-fd587780-7f40-11eb-8728-bdc61e1e89f6.png)

**Comment by ckhmer1** [comment]
Fixed

**Comment by rockstar2020** [comment]
Thanks,
The error is now gone when executing the command but please note that I still get the same error whenever I save my nodes.
Not a big deal as long as my commands are executed properly so this is just FYI in case you wanted to investigate this issue as well.
Appreciate it!

Cheers

**Comment by ckhmer1** [comment]
Hi,
I'm sorry but I'm not able to reproduce the problem.
Could You please tell me how to do it?
Thanks

**Comment by rockstar2020** [comment]
Sorry, I did my best to investigate further but don't know where this error is coming from.
But whenever I click "Deploy" in Node-Red (even with no changes) the following message is appearing on my debug window.
I even tried to revert all recent changes back to what it was before but still don't know where the issue may come from.
As I said this error does not come when the commend is sent to Node-Red for execution so not a really big deal but I am intersted to troubelshoot it.

Thank you for your support.

![image](https://user-images.githubusercontent.com/35903046/110256260-dd877a80-7f65-11eb-9035-a8cd36be4df1.png)

**Comment by ckhmer1** [comment]
Hi,
Are You sure You have copied all the fix correctly? Because I cannot reproduce it, clicking the deploy button.

**Comment by rockstar2020** [comment]
Hi,
Sorry for my late reply.
I did try the new fix and now everything works perfect.

Much appreciate it!

Cheers
