### ISSUE TITLE
Send 'announcements' to google home

### ISSUE THREAD

**Issue by Paul-Reed** [mikejac/node-red-contrib-google-smarthome#153]
Is it possible to send an 'announcement' command to google home using smarthome?
Possible uses could include providing audible feedback following smarthome actions, such as announcing a doorbell, fire alarm message, or just general information.
We could of course 'cast' messages, instead of making 'announcements', but there are many problems with casting, [such as this issue](https://discourse.nodered.org/t/help-google-home-return-to-play-music-after-announcement/46763) raised by another user in the node-RED forum.

_If this is straying away from intended use of smarthome - please close._

**Comment by ckhmer1** [comment]
Hi,
the following node traits support the notifications:

ObjectDetection
RunCycle
SensorState
LockUnlock
NetworkControl
OpenClose
To send a message, just send a message to the node with a topic ending with one of the previous trait names and the payload the right content (see the trait documentation).

The plugin for those nodes sets the attribute notificationSupportedByAgent to true.

Unfortunately, this seems not to be enough to have a notification, and I don't understand what's missing.

Are You able to review the notification hoping You find some error?

Thanks
Claudio

**Comment by Paul-Reed** [comment]
Thanks Claudio
I'm sorry, but although I understand the examples that you have provided in the readme, I don't understand the link between the trait documentation and smarthome, and what format the incoming message should take.
I've spent this evening reading the google documentation, but don't really understand it.
Hopefully, at some stage a working example may be available which I could follow.

Thanks for the quick reply.

**Comment by ckhmer1** [comment]
Hi,
just use the following node and send the message to a google node with Object Detection trait:

`
[{"id":"548f006a.2ea9d","type":"inject","z":"52f01081.f54d1","name":"Object Detection","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":"10","topic":"ObjectDetection","payload":"{\"unclassified\":2}","payloadType":"json","x":120,"y":1680,"wires":[["43a13163.4a3e6"]]}]
`

This sends a notification to Google Home, unfortunately, it is not working for me.

**Comment by Caprico85** [comment]
`notificationSupportedByAgent` was declared on the wrong level. Fixed that in 6df0c4570e3764dedda16fd3fbd711ed9b8684f3.

Still can't get it to work though. I only get a totally helpful "GENERIC_ERROR" in Google Cloud Platform logs.

**Comment by ckhmer1** [comment]
Hi,
did You enable the ObjectDetection trait in the node?
I moved the notificationSUpportedByAgent, but no luck yet (but no error).
Below the log:

google-smarthome:DeviceNode.input: topic = ObjectDetection
Devices:SendNotifications(): notifications = {"ObjectDetection":{"objects":{"unclassified":2},"priority":0,"detectionTimestamp":1623217204778}}
HttpActions:reportState(): deviceId = 43a13163.4a3e6
HttpActions:reportState(): states = undefined
HttpActions:reportState(): notifications = {"ObjectDetection":{"objects":{"unclassified":2},"priority":0,"detectionTimestamp":1623217204778}}
HttpActions:reportState(): postData = {"requestId":"4ZiAIzMM46AsWHmxa8mZWC","agentUserId":"0","payload":{"devices":{"notifications":{"43a13163.4a3e6":{"ObjectDetection":{"objects":{"unclassified":2},"priority":0,"detectionTimestamp":1623217204778}}}}},"eventId":"67buB00O5rKvNgKu2XND8B"}
HttpActions:reportState(): success

**Comment by Caprico85** [comment]
Node-Red's log shows "success" for me too. I'm sseing this error in GCP logs.

```
{
  "insertId": "b3rv3ug9oa0330",
  "jsonPayload": {
    "notificationLog": {
      "notifications": [
        {
          "status": "GENERIC_ERROR",
          "structType": "ObjectDetection"
        }
      ],
      "requestId": "7FnoGWZkVP5W6TOJmxZNts"
    }
  },
  "resource": {
    "type": "assistant_action_project",
    "labels": {
      "project_id": "xxxxxxxxxxxxx"
    }
  },
  "timestamp": "2021-06-09T04:44:45.546054411Z",
  "severity": "ERROR",
  "logName": "projects/xxxxxxxxxxxxx/logs/assistant_smarthome%2Fassistant_smarthome_logs",
  "receiveTimestamp": "2021-06-09T04:44:45.546054411Z"
}
```

I did enable ObjectDetection. I have a doorbell defined like this:

```[{"id":"548f006a.2ea9d","type":"inject","z":"1fdba310.d04cad","name":"Object Detection","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":"10","topic":"ObjectDetection","payload":"{\"unclassified\":2}","payloadType":"json","x":700,"y":920,"wires":[["bf78ee9a.3d923"]]},{"id":"bf78ee9a.3d923","type":"google-device","z":"1fdba310.d04cad","client":"","name":"Testklingel","topic":"klingel","room_hint":"Wohnzimmer","device_type":"DOORBELL","trait_appselector":false,"trait_channel":false,"trait_inputselector":false,"trait_mediastate":false,"trait_onoff":false,"trait_transportcontrol":false,"trait_modes":false,"trait_volume":false,"trait_toggles":false,"trait_brightness":false,"trait_colorsetting":false,"appselector_file":"applications.json","channel_file":"channels.json","inputselector_file":"inputs.json","command_only_input_selector":false,"ordered_inputs":false,"support_activity_state":false,"support_playback_state":false,"command_only_onoff":false,"query_only_onoff":false,"supported_commands":["CAPTION_CONTROL","NEXT","PAUSE","PREVIOUS","RESUME","SEEK_RELATIVE","SEEK_TO_POSITION","SET_REPEAT","SHUFFLE","STOP"],"volume_max_level":100,"can_mute_and_unmute":true,"volume_default_percentage":40,"level_step_size":1,"command_only_volume":false,"command_only_brightness":false,"command_only_colorsetting":false,"color_model":"temp","temperature_min_k":2000,"temperature_max_k":9000,"modes_file":"modes.json","command_only_modes":false,"query_only_modes":false,"toggles_file":"toggles.json","command_only_toggles":false,"query_only_toggles":false,"trait_camerastream":false,"hls":"","hls_app_id":"","dash":"","dash_app_id":"","smooth_stream":"","smooth_stream_app_id":"","progressive_mp4":"","progressive_mp4_app_id":"","auth_token":"","passthru":false,"trait_scene":false,"scene_reversible":true,"trait_timer":false,"trait_temperaturesetting":false,"max_timer_limit_sec":86400,"command_only_timer":false,"available_thermostat_modes":["off","heat","cool","on","heatcool","auto","fan-only","purifier","eco","dry"],"min_threshold_celsius":0,"max_threshold_celsius":40,"thermostat_temperature_unit":"C","buffer_range_celsius":2,"command_only_temperaturesetting":false,"query_only_temperaturesetting":false,"trait_temperaturecontrol":false,"tc_min_threshold_celsius":0,"tc_max_threshold_celsius":40,"tc_temperature_step_celsius":1,"tc_temperature_unit_for_ux":"C","tc_command_only_temperaturecontrol":false,"tc_query_only_temperaturecontrol":false,"trait_humiditysetting":false,"min_percent":0,"max_percent":100,"command_only_humiditysetting":false,"query_only_humiditysetting":false,"trait_dock":false,"trait_locator":false,"trait_lockunlock":false,"trait_reboot":false,"trait_openclose":false,"discrete_only_openclose":false,"open_direction":[],"command_only_openclose":false,"query_only_openclose":false,"trait_startstop":false,"pausable":false,"available_zones":[],"lang":"de","trait_runcycle":false,"trait_softwareupdate":false,"trait_rotation":false,"supports_degrees":true,"supports_percent":true,"rotation_degrees_min":0,"rotation_degrees_max":360,"supports_continuous_rotation":false,"command_only_rotation":false,"trait_lighteffects":false,"default_sleep_duration":1800,"default_wake_duration":1800,"supported_effects":["colorLoop","sleep","wake"],"trait_statusreport":false,"trait_cook":false,"supported_cooking_modes":[],"food_presets_file":"foodPresets.json","trait_fanspeed":false,"reversible":false,"supports_fan_speed_percent":false,"fan_speeds_ordered":false,"command_only_fanspeed":false,"available_fan_speeds_file":"availableFanSpeeds.json","trait_sensorstate":false,"sensor_states_supported":[],"arm_levels_ordered":false,"trait_fill":false,"available_fill_levels_file":"availableFillLevels.json","supports_fill_percent":false,"trait_armdisarm":false,"available_arm_levels_file":"availableArmLevels.json","trait_energystorage":false,"is_rechargeable":false,"query_only_energy_storage":false,"energy_storage_distance_unit_for_ux":"KILOMETERS","trait_dispense":false,"supported_dispense_items_file":"supportedDispenseItems.json","supported_dispense_presets_file":"supportedDispensePresets.json","trait_networkcontrol":false,"supports_enabling_guest_network":false,"supports_disabling_guest_network":false,"supports_getting_guest_network_password":false,"network_profiles":[],"supports_enabling_network_profile":false,"supports_disabling_network_profile":false,"supports_network_download_speedtest":false,"supports_network_upload_speedtest":false,"trait_objectdetection":true,"show_trait":"recommended","advanced_settings":false,"x":960,"y":920,"wires":[[]]}]```

**Comment by Paul-Reed** [comment]
After updating to v0.0.70 I no longer get an error in the node-RED log;
```
google-smarthome:DeviceNode.input: topic = ObjectDetection
Devices:SendNotifications(): notifications = {"ObjectDetection":{"objects":{"unclassified":2},"priority":0,"detectionTimestamp":1623227877735}}
HttpActions:reportState(): deviceId = f1cd148f.30dfe8
HttpActions:reportState(): states = undefined
HttpActions:reportState(): notifications = {"ObjectDetection":{"objects":{"unclassified":2},"priority":0,"detectionTimestamp":1623227877735}}
HttpActions:reportState(): postData = {"requestId":"14YEdCnzXXXXXX59KWW5","agentUserId":"0","payload":{"devices":{"notifications":{"f1cd148f.30dfe8":{"ObjectDetection":{"objects":{"unclassified":2},"priority":0,"detectionTimestamp":1623227877735}}}}},"eventId":"6IIpnJfJ91UW8G4De89wdn"}
HttpActions:reportState(): success
```
But in the Google Cloud log I see this error;
```
{
  "insertId": "16qki4hg2xuobwk",
  "jsonPayload": {
    "notificationLog": {
      "requestId": "35R9Rwz5tG2IQy1FdjDYT6",
      "notifications": [
        {
          "status": "NOTIFICATION_SUPPORTED_BY_AGENT_MISSING",
          "structType": "ObjectDetection"
        }
      ]
    }
  },
  "resource": {
    "type": "assistant_action_project",
    "labels": {
      "project_id": "pauls-smarthome"
    }
  },
  "timestamp": "2021-06-09T08:28:12.787847050Z",
  "severity": "ERROR",
  "logName": "projects/pauls-smarthome/logs/assistant_smarthome%2Fassistant_smarthome_logs",
  "receiveTimestamp": "2021-06-09T08:28:12.787847050Z"
}
```

**Comment by Caprico85** [comment]
I released v0.0.71 including the fix to NOTIFICATION_SUPPORTED_BY_AGENT_MISSING.

**Comment by Paul-Reed** [comment]
v0.0.71 has fixed the "NOTIFICATION_SUPPORTED_BY_AGENT_MISSING" problem, but the google log is still showing an error which is the same as @Caprico85 ;
```
{
  "insertId": "1t7iXXXXXXXXXxlp0",
  "jsonPayload": {
    "notificationLog": {
      "notifications": [
        {
          "status": "GENERIC_ERROR",
          "structType": "ObjectDetection"
        }
      ],
      "requestId": "2l4MV2XXXXXXXXXxmCWjm"
    }
  },
  "resource": {
    "type": "assistant_action_project",
    "labels": {
      "project_id": "pauls-smarthome"
    }
  },
  "timestamp": "2021-06-09T12:46:15.407649939Z",
  "severity": "ERROR",
  "logName": "projects/pauls-smarthome/logs/assistant_smarthome%2Fassistant_smarthome_logs",
  "receiveTimestamp": "2021-06-09T12:46:15.407649939Z"
}
```

**Comment by ckhmer1** [comment]
Hi,
thank you for sharing the update.
Could You please share with me how to Google Cloud Platform logs?

I've used the key already created for the project, used for sending the "reportState" message, following the info: [Notifications for smart home Actions](https://developers.google.com/assistant/smarthome/develop/notifications)

I think this key should be valid also for the notifications.

I don't understand what is missing or wrong.

Thanks

**Comment by Caprico85** [comment]
For GCP logs go to Google Actions Console, tab `Test`, then "Logs in Google Cloud". Possibly also on https://console.cloud.google.com/logs/.

So far I didn't found a solution for the GENERIC_ERROR. Seems nobody else had a similar problem.

One thing I don't understand: It says you have to enable notifications on your smart speaker/display like described on https://support.google.com/googlenest/answer/7550525/turn-nest-displays-notifications-on-or-off-android. I don't even have these settings

**Comment by Paul-Reed** [comment]
I'm assuming that those options only relate to 'shared devices'.
![google](https://user-images.githubusercontent.com/973580/121407963-c3d84380-c957-11eb-8972-22e092eda1ac.png)

**Comment by ckhmer1** [comment]
Hi,

I've found where to enable the notification, just open the Google Home app, click on a device enabled to send the notification, and enable it. See the image bellow:

![image](https://user-images.githubusercontent.com/2863760/123489788-03b75000-d613-11eb-96b1-fe0774e2826c.png)


I've checked the logs, I get the following entry:


```
{
  "insertId": "13yobn5froxrp0",
  "jsonPayload": {
    "notificationLog": {
      "notifications": [
        {
          "status": "**SUCCESS**",
          "structType": "ObjectDetection"
        }
      ],
      "requestId": "5oIMMcxBWk8Jy5uacCRuSO"
    }
  },
  "resource": {
    "type": "assistant_action_project",
    "labels": {
      "project_id": "XXXXXXX"
    }
  },
  "timestamp": "2021-06-25T21:42:38.559361759Z",
  "severity": "DEBUG",
  "logName": "projects/XXXXXXX/logs/assistant_smarthome%2Fassistant_smarthome_logs",
  "receiveTimestamp": "2021-06-25T21:42:38.559361759Z"
}
```

**Comment by Paul-Reed** [comment]
Can you share your test flow please.

**Comment by ckhmer1** [comment]
Here it is.

```
[
    {
        "id": "43a13163.4a3e6",
        "type": "google-device",
        "z": "52f01081.f54d1",
        "client": "1884daf7.785005",
        "name": "Campanello",
        "topic": "",
        "room_hint": "Ingresso",
        "device_type": "DOORBELL",
        "trait_appselector": false,
        "trait_channel": false,
        "trait_inputselector": false,
        "trait_mediastate": false,
        "trait_onoff": false,
        "trait_transportcontrol": false,
        "trait_modes": false,
        "trait_volume": false,
        "trait_toggles": false,
        "trait_brightness": false,
        "trait_colorsetting": false,
        "appselector_file": "applications.json",
        "channel_file": "channels.json",
        "inputselector_file": "inputs.json",
        "command_only_input_selector": false,
        "ordered_inputs": false,
        "support_activity_state": false,
        "support_playback_state": false,
        "command_only_onoff": false,
        "query_only_onoff": false,
        "supported_commands": [
            "CAPTION_CONTROL",
            "NEXT",
            "PAUSE",
            "PREVIOUS",
            "RESUME",
            "SEEK_RELATIVE",
            "SEEK_TO_POSITION",
            "SET_REPEAT",
            "SHUFFLE",
            "STOP"
        ],
        "volume_max_level": 100,
        "can_mute_and_unmute": true,
        "volume_default_percentage": 40,
        "level_step_size": 1,
        "command_only_volume": false,
        "command_only_brightness": false,
        "command_only_colorsetting": false,
        "color_model": "temp",
        "temperature_min_k": 2000,
        "temperature_max_k": 9000,
        "modes_file": "modes.json",
        "command_only_modes": false,
        "query_only_modes": false,
        "toggles_file": "toggles.json",
        "command_only_toggles": false,
        "query_only_toggles": false,
        "trait_camerastream": false,
        "hls": "",
        "hls_app_id": "",
        "dash": "",
        "dash_app_id": "",
        "smooth_stream": "",
        "smooth_stream_app_id": "",
        "progressive_mp4": "",
        "progressive_mp4_app_id": "",
        "auth_token": "",
        "passthru": false,
        "trait_scene": false,
        "scene_reversible": true,
        "trait_timer": false,
        "trait_temperaturesetting": false,
        "max_timer_limit_sec": 86400,
        "command_only_timer": false,
        "available_thermostat_modes": [
            "off",
            "heat",
            "cool",
            "on",
            "heatcool",
            "auto",
            "fan-only",
            "purifier",
            "eco",
            "dry"
        ],
        "min_threshold_celsius": "10",
        "max_threshold_celsius": "32",
        "thermostat_temperature_unit": "C",
        "buffer_range_celsius": 2,
        "command_only_temperaturesetting": false,
        "query_only_temperaturesetting": false,
        "trait_temperaturecontrol": false,
        "tc_min_threshold_celsius": 0,
        "tc_max_threshold_celsius": 40,
        "tc_temperature_step_celsius": 1,
        "tc_temperature_unit_for_ux": "C",
        "tc_command_only_temperaturecontrol": false,
        "tc_query_only_temperaturecontrol": false,
        "trait_humiditysetting": false,
        "min_percent": 0,
        "max_percent": 100,
        "command_only_humiditysetting": false,
        "query_only_humiditysetting": false,
        "trait_dock": false,
        "trait_locator": false,
        "trait_lockunlock": false,
        "trait_reboot": false,
        "trait_openclose": false,
        "discrete_only_openclose": false,
        "open_direction": [],
        "command_only_openclose": false,
        "query_only_openclose": false,
        "trait_startstop": false,
        "pausable": false,
        "available_zones": [],
        "lang": "it",
        "trait_runcycle": false,
        "trait_softwareupdate": false,
        "trait_rotation": false,
        "supports_degrees": true,
        "supports_percent": true,
        "rotation_degrees_min": 0,
        "rotation_degrees_max": 360,
        "supports_continuous_rotation": false,
        "command_only_rotation": false,
        "trait_lighteffects": false,
        "default_sleep_duration": 1800,
        "default_wake_duration": 1800,
        "supported_effects": [
            "colorLoop",
            "sleep",
            "wake"
        ],
        "trait_statusreport": false,
        "trait_cook": false,
        "supported_cooking_modes": [],
        "food_presets_file": "foodPresets.json",
        "trait_fanspeed": false,
        "reversible": false,
        "supports_fan_speed_percent": true,
        "fan_speeds_ordered": true,
        "command_only_fanspeed": false,
        "available_fan_speeds_file": "availableFanSpeeds.json",
        "trait_sensorstate": false,
        "sensor_states_supported": [],
        "arm_levels_ordered": true,
        "trait_fill": false,
        "available_fill_levels_file": "availableFillLevels.json",
        "supports_fill_percent": false,
        "trait_armdisarm": false,
        "available_arm_levels_file": "availableArmLevels.json",
        "trait_energystorage": false,
        "is_rechargeable": false,
        "query_only_energy_storage": false,
        "energy_storage_distance_unit_for_ux": "KILOMETERS",
        "trait_dispense": false,
        "supported_dispense_items_file": "supportedDispenseItems.json",
        "supported_dispense_presets_file": "supportedDispensePresets.json",
        "trait_networkcontrol": false,
        "supports_enabling_guest_network": false,
        "supports_disabling_guest_network": false,
        "supports_getting_guest_network_password": false,
        "network_profiles": [],
        "supports_enabling_network_profile": false,
        "supports_disabling_network_profile": false,
        "supports_network_download_speedtest": false,
        "supports_network_upload_speedtest": false,
        "trait_objectdetection": true,
        "show_trait": "selected",
        "advanced_settings": false,
        "x": 440,
        "y": 1640,
        "wires": [
            [
                "8b31ef13.3492"
            ]
        ]
    },
    {
        "id": "b20005f.91069f8",
        "type": "inject",
        "z": "52f01081.f54d1",
        "name": "Object Detection",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": "10",
        "topic": "ObjectDetection",
        "payload": "{\"named\":\"Alice\"}",
        "payloadType": "json",
        "x": 120,
        "y": 1640,
        "wires": [
            [
                "43a13163.4a3e6"
            ]
        ]
    },
    {
        "id": "548f006a.2ea9d",
        "type": "inject",
        "z": "52f01081.f54d1",
        "name": "Object Detection",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": "10",
        "topic": "ObjectDetection",
        "payload": "{\"unclassified\":2}",
        "payloadType": "json",
        "x": 120,
        "y": 1680,
        "wires": [
            [
                "43a13163.4a3e6"
            ]
        ]
    },
    {
        "id": "8b31ef13.3492",
        "type": "debug",
        "z": "52f01081.f54d1",
        "name": "Campanello",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 650,
        "y": 1640,
        "wires": []
    },
    {
        "id": "1884daf7.785005",
        "type": "googlesmarthome-client",
        "name": "",
        "enabledebug": true,
        "usegooglelogin": true,
        "usehttpnoderoot": false,
        "port": "",
        "httppath": "google",
        "ssloffload": true,
        "accesstokenduration": "30",
        "reportinterval": "50"
    }
]
```

**Comment by Paul-Reed** [comment]
Yes! I have it working from your flow!!!
That is a very welcome addition to Smarthome, thank you for your help @ckhmer1 
:relaxed: :relaxed: :relaxed:

**Comment by ckhmer1** [comment]
I'm glad to improve it

**Comment by Caprico85** [comment]
Got it working too 👍

I added a note on how to setup notifications to Readme. I'll close this issue now.

**Comment by FireWizard52** [comment]
Hi all,

As Smoke alarms (Smoke detectors) are mandatory in many countries, it is a good idea to use an announcement to your Google Home speakers in case smoke has been detected.

It is rather difficult to find in the Google documentation on how the payload should look like.
Please find below an example of how to send a notification to your Google speaker in case smoke has been detected.

`[{"id":"b89c356b30f2a00e","type":"google-device","z":"1797c1fc2aa93477","client":"d7ec4b2f72adc483","name":"Rookmelder","nicknames":"Smoke Alarm","topic":"","room_hint":"Test","device_type":"SMOKE_DETECTOR","trait_appselector":false,"trait_channel":false,"trait_inputselector":false,"trait_mediastate":false,"trait_onoff":false,"trait_transportcontrol":false,"trait_modes":false,"trait_volume":false,"trait_toggles":false,"trait_brightness":false,"trait_colorsetting":false,"appselector_file":"applications_<id>.json","appselector_type":"str","channel_file":"channels_<id>.json","channel_type":"str","inputselector_file":"inputs_<id>.json","inputselector_type":"str","command_only_input_selector":false,"ordered_inputs":false,"support_activity_state":false,"support_playback_state":false,"command_query_onoff":"","supported_commands":["CAPTION_CONTROL","NEXT","PAUSE","PREVIOUS","RESUME","SEEK_RELATIVE","SEEK_TO_POSITION","SET_REPEAT","SHUFFLE","STOP"],"volume_max_level":100,"volume_can_mute_and_unmute":true,"volume_default_percentage":40,"level_step_size":1,"command_only_volume":false,"command_only_brightness":false,"command_only_colorsetting":false,"color_model":"temp","temperature_min_k":2000,"temperature_max_k":9000,"modes_file":"modes_<id>.json","modes_type":"str","command_query_modes":"","toggles_file":"toggles_<id>.json","toggles_type":"str","command_query_toggles":"","trait_camerastream":false,"hls":"","hls_app_id":"","dash":"","dash_app_id":"","smooth_stream":"","smooth_stream_app_id":"","progressive_mp4":"","progressive_mp4_app_id":"","webrtc":"","webrtc_offer":"","webrtc_ice_servers":"","webrtc_ice_servers_type":"str","auth_token":"","passthru":false,"persistent_state":true,"trait_scene":false,"scene_reversible":true,"trait_timer":false,"trait_temperaturesetting":false,"max_timer_limit_sec":86400,"command_only_timer":false,"available_thermostat_modes":["off","heat","cool","on","heatcool","auto","fan-only","purifier","eco","dry"],"min_threshold_celsius":0,"max_threshold_celsius":40,"thermostat_temperature_unit":"C","buffer_range_celsius":2,"command_query_temperaturesetting":"","trait_temperaturecontrol":false,"tc_min_threshold_celsius":0,"tc_max_threshold_celsius":40,"tc_temperature_step_celsius":1,"tc_temperature_unit_for_ux":"C","tc_command_query_temperaturecontrol":"","trait_humiditysetting":false,"min_percent":0,"max_percent":100,"command_query_humiditysetting":"","trait_dock":false,"trait_locator":false,"trait_lockunlock":false,"trait_reboot":false,"trait_openclose":false,"discrete_only_openclose":false,"open_direction":[],"command_query_openclose":"","trait_startstop":false,"pausable":false,"available_zones":[],"trait_runcycle":false,"trait_softwareupdate":false,"trait_rotation":false,"supports_degrees":true,"supports_percent":true,"rotation_degrees_min":0,"rotation_degrees_max":360,"supports_continuous_rotation":false,"command_only_rotation":false,"trait_lighteffects":false,"default_sleep_duration":1800,"default_wake_duration":1800,"supported_effects":["colorLoop","sleep","wake"],"trait_statusreport":false,"trait_cook":false,"supported_cooking_modes":[],"food_presets_file":"foodPresets_<id>.json","food_presets_type":"str","trait_fanspeed":false,"reversible":false,"supports_fan_speed_percent":false,"fan_speeds_ordered":false,"command_only_fanspeed":false,"available_fan_speeds_file":"availableFanSpeeds_<id>.json","available_fan_speeds_type":"str","trait_sensorstate":true,"sensor_states_supported":["SmokeLevel"],"arm_levels_ordered":false,"trait_fill":false,"available_fill_levels_file":"availableFillLevels_<id>.json","available_fill_levels_type":"str","supports_fill_percent":false,"ordered_fill_levels":true,"trait_armdisarm":false,"available_arm_levels_file":"availableArmLevels_<id>.json","available_arm_levels_type":"str","trait_energystorage":false,"is_rechargeable":false,"query_only_energy_storage":false,"energy_storage_distance_unit_for_ux":"","trait_dispense":false,"supported_dispense_items_file":"supportedDispenseItems_<id>.json","supported_dispense_items_type":"str","supported_dispense_presets_file":"supportedDispensePresets_<id>.json","supported_dispense_presets_type":"str","trait_networkcontrol":false,"supports_enabling_guest_network":false,"supports_disabling_guest_network":false,"supports_getting_guest_network_password":false,"network_profiles":[],"supports_enabling_network_profile":false,"supports_disabling_network_profile":false,"supports_network_download_speedtest":false,"supports_network_upload_speedtest":false,"trait_objectdetection":false,"show_trait":"selected","advanced_settings":true,"ct_appselector":"","ct_armdisarm":"","ct_brightness":"","ct_camerastream":"","ct_channel":"","ct_colorsetting":"","ct_cook":"","ct_dispense":"","ct_dock":"","ct_energystorage":"","ct_fanspeed":"","ct_fill":"","ct_humiditysetting":"","ct_inputselector":"","ct_lighteffects":"","ct_locator":"","ct_lockunlock":"","ct_mediastate":"","ct_modes":"","ct_networkcontrol":"","ct_objectdetection":"","ct_onoff":"","ct_openclose":"","ct_reboot":"","ct_rotation":"","ct_runcycle":"","ct_scene":"","ct_sensorstate":"","ct_softwareupdate":"","ct_startstop":"","ct_statusreport":"","ct_temperaturecontrol":"","ct_temperaturesetting":"","ct_timer":"","ct_toggles":"","ct_transportcontrol":"","ct_volume":"","pin_appselector":"","pin_armdisarm":"","pin_brightness":"","pin_camerastream":"","pin_channel":"","pin_colorsetting":"","pin_cook":"","pin_dispense":"","pin_dock":"","pin_energystorage":"","pin_fanspeed":"","pin_fill":"","pin_humiditysetting":"","pin_inputselector":"","pin_lighteffects":"","pin_locator":"","pin_lockunlock":"","pin_mediastate":"","pin_modes":"","pin_networkcontrol":"","pin_objectdetection":"","pin_onoff":"","pin_openclose":"","pin_reboot":"","pin_rotation":"","pin_runcycle":"","pin_scene":"","pin_sensorstate":"","pin_softwareupdate":"","pin_startstop":"","pin_statusreport":"","pin_temperaturecontrol":"","pin_temperaturesetting":"","pin_timer":"","pin_toggles":"","pin_transportcontrol":"","pin_volume":"","x":500,"y":3040,"wires":[[]]},{"id":"148aa41effefe119","type":"inject","z":"1797c1fc2aa93477","name":"Smoke","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"currentSensorStateData\":[{\"name\":\"SmokeLevel\",\"currentSensorState\":\"smoke detected\"}]}","payloadType":"json","x":270,"y":3040,"wires":[["b89c356b30f2a00e"]]},{"id":"6b7581b806fc2662","type":"inject","z":"1797c1fc2aa93477","name":"No Smoke","props":[{"p":"payload"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"currentSensorStateData\":[{\"name\":\"SmokeLevel\",\"currentSensorState\":\"no smoke detected\"}]}","payloadType":"json","x":260,"y":3080,"wires":[["b89c356b30f2a00e"]]},{"id":"17794bef0894967a","type":"inject","z":"1797c1fc2aa93477","name":"Smoke Notification","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"SensorState","payload":"{\"name\":\"SmokeLevel\",\"priority\":0,\"currentSensorState\":\"smoke detected\"}","payloadType":"json","x":230,"y":3000,"wires":[["b89c356b30f2a00e"]]},{"id":"d7ec4b2f72adc483","type":"googlesmarthome-client","name":"Jonas","enabledebug":false,"default_lang":"en","usegooglelogin":true,"usehttpnoderoot":false,"port":"3001","httppath":"","ssloffload":false,"localport":"18080","accesstokenduration":"60","reportinterval":"60","request_sync_delay":"2","set_state_delay":"2"}]`

It would be niice, if we would been able to add the location of the moke detector.
Anyone an idea?
