### ISSUE TITLE
v0.3.6 drops connection after 30-60 minute period

### ISSUE THREAD

**Issue by ChutneyMary** [mikejac/node-red-contrib-google-smarthome#290]
I've just updated to v0.3.6. Voice control works fine for about 30 to 60 minutes. Then, when a subsequent voice command is given, I get the message - "Sorry, it looks like 'my project name' is unavailable now."
If I unlink the account, then relink the account, all works fine for another period of about 30 to 60 minutes.
I've tried using the command "Sync my devices", but that delivers the message - "Sorry, something went wrong when syncing 'my project name' etc.
Only an unlink and relink of the account resumes normal service.
Any suggestions for what information I can provide for further fault-finding?

**Comment by Caprico85** [comment]
Sounds like a problem with access token renewal. I'll look into it.

What did you set as access token duration in your config? I guess it's 30 to 60 minutes. 

![image](https://user-images.githubusercontent.com/2081806/173239954-c86611b9-804d-41aa-8acd-38bd329c1f0a.png)

As a workaround you can set this to a high value. E.g. 10080 minutes = 1 week. Then you only should have to relogin after 1 week.

**Comment by Caprico85** [comment]
As expected, I messed up token renewal in my latest updates. Sorry for that.
Should be fixed in v0.3.7

**Comment by FireWizard52** [comment]
Hello @Caprico85 

I noticed the same thing with version 0.3.6. So I updated to version 0.3.7.
Followed by a restart ofNode-RED.
After a few minutes a lot of devices are going "Offline" A restart of Node-RED solves it again
But then it repeats again. After a "Voice" request, it responds with "The Projectname seems to be unreachable"

**Comment by Paul-Reed** [comment]
For info: I updated from v0.3.5 to 0.3.7 earlier tonight, restarted node-RED, and all devices have remained online, and are fully functional.

**Comment by FireWizard52** [comment]
Thanks for the information, Paul.
I restarted NR for the last time about 1.5 hours ago and so far all devices are still online.
Everything seems to work now, including "local execution".
I think, that after update from 0.3.6 to 0.3.7 I had to restart NR 3 times, but so far it is still working.
So let's wait till tomorrow.

**Comment by FireWizard52** [comment]
Sorry to say,

All the devices were "offline" again and, if a voice command was given, the response was that the "ProjectName" was not reachable.
But restarting the server solved the issue for this moment, (Inject topic "restart_server" in the Configuration node)
Let's wait, how long it lasts.

**Comment by FireWizard52** [comment]
Not that long, offline again and this time restart server did not work and I had to restart NR.

**Comment by Paul-Reed** [comment]
Are you sure that the upgrade to v0.3.7 was completed OK?

**Comment by FireWizard52** [comment]
Hello Paul,

How can someone be sure? I updated the node through the palette (not the commandline). Both updates, to 0.3.6 and to 0.3.7, did ended normally and so I may assume that the updates are correct.

This morning I found that the devices were still offline, but they went online later. I decided to reconnect and since then (about 0.5 hours) they are still online.

Let's wait.

Regards

**Comment by Paul-Reed** [comment]
@FireWizard52 The node-RED 'manage palette' should show the version number of the smarthome node which is currently installed, because it reads the smarthome node's package.json directly.

**Comment by merlinschumacher** [comment]
The upgrade also didn't fix the issue for me.  The devices remain offline, after I've restarted nodered.

**Comment by merlinschumacher** [comment]
I've updated to 0.3.7 and had to relink Node-Red in the Google Home app to get it working again.

**Comment by FireWizard52** [comment]
Hello @Paul-Reed,

You said:

> @FireWizard52 The node-RED 'manage palette' should show the version number of the smarthome node which is currently installed, because it reads the smarthome node's package.json directly.
 
Yes, It indicates 0.3.7. I always check that, if I update a node. So that is not the problem

Since I reconnected my account, no issues has been observed and all devices are online and working.
I assume it is solved and it looks that @merlinschumacher has had the same problem.

Regards

**Comment by Caprico85** [comment]
Sorry, was away for a few days. So, anybody still having problems?

After updating to 0.3.7 and relinking the account this should be fixed.

In case the problem persists:
- With debug mode enabled in the management node, do you see any messages in Node-RED's log output when you try to control your devices? That is, is Google actually trying to connect your server?
- Do you see any error messages in [Google Cloud Logs}(https://console.cloud.google.com/logs/)?

**Comment by FireWizard52** [comment]
Hello @Caprico85,

I hope you had some nice days.
I do not have any issue at the moment.
S
So thanks for your attention.

Regards

**Comment by Caprico85** [comment]
Good to see this is fixed now.
