### ISSUE TITLE
Getting Error 400 after external update [INVALID_ARGUMENT on Thermostat]

### ISSUE THREAD

**Issue by Aragur** [mikejac/node-red-contrib-google-smarthome#72]
Same issue as with the light. (Lights are now fixed)  
What are the steps to fix this? Are there any external docs available?
![Screenshot_20201206_203010](https://user-images.githubusercontent.com/11004008/101290383-27937f80-3802-11eb-899a-7a0c3a9c7e70.png)

**Comment by Caprico85** [comment]
The problem is the field named `current_heating_setpoint`. But I wonder how it got there.
The node does not set a field with this name by itself so it must be injected somehow. But I never managed to inject a field with this name. Neither by injecting topic+value, nor by injecting it as object.

**Comment by Chrischi-** [comment]
@Caprico85 @Aragur 
I think this issue can be closed.

Should be solved with PR #80. Before that foreign payload could be leaked into reportState.

Happened to me several times and was the basis for the PR.

**Comment by Caprico85** [comment]
> I think this issue can be closed.

I'm not sure about that. I thought #80 only fixes `command` leaking into reportState(). But here, the problem seems to be the field named `current_heating_setpoint`.

I still do not understand where `current_heating_setpoint`comes from. It is neither sent by Google nor is it defined somewhere in `node-red-contrib-google-smarthome`. So it was probably sent as an input to the device node. But inputs are already filtered.

**Comment by Aragur** [comment]
Hey sorry for my late answer..

@Chrischi- it wasn't fixed with #80

Still having the same issue with the latest version.
I also don't know where `current_heating_setpoint` comes from.
My Zigbee2MQTT Thermostat uses this value, but I checked my injected payload doesn't contain this value after my conversition.
So I have no clue. Also this error is triggered only when I update the thermostat via the Google Assistant not via an injection.

**Comment by Chrischi-** [comment]
I think this comes from the fact that `command` && `states` is used multiple times in the flow. Also from the target node. In this case a thermostat. 

This has happened to me several times when the flow behind the GA node is processed further, e.g. move / change payload etc.

The problem has been solved at my flows with the PR #80.

For me, this was the root of the problem that leaked foreign payload into the reportState() payload: `curDevice.states['command'] = command.command;`

@Aragur @Caprico85 
as mentioned in PR #80, this change must also be rolled out to all devices. I have only done this for my shutter device as an example. Since this had reproducible the same problem.

I will implement this later for the thermostat device. Then you can test.

**Comment by Caprico85** [comment]
Released v0.0.53 with @Chrischi-'s PR #80 and my additions.

**Comment by Chrischi-** [comment]
@Caprico85 
now with your move to classes with release v0.0.54 the problem should be finally solved.
